### PR TITLE
Skeleton Loader 

### PR DESCRIPTION
**Pull request by siradji**
#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:
Added Skeleton loader to supply stats - Created reusable text-based loader component
#### Which issue(s) does this PR fixes?:

Fixes #

#### Sample Links & Screenshots:

Link: 
<details>
<summary>Desktop Screenshot</summary>

</details>
<details>
<summary>Mobile Screenshot</summary>

</details>

#### Developer Checklist:

- [ ] Read your code changes at least once
- [ ] Tested on multiple web browsers
- [ ] Tested responsiveness (e.g, iPhone, iPad, Desktop)
- [ ] No console errors
- [ ] Unit tests*
- [ ] Added e2e tests*

### CODE REVIEW

**Review by joeldavidw — CHANGES_REQUESTED** [review]
Lets create a skeleton loader component which should allow for custom height and length.

**Comment by joeldavidw** [comment]
Maybe we could make use of tailwind font-size to determine the height required for the loader. Just an example, the component could take in the expected text to determine the height and width of the loader but keep the text hidden.

Let me know what you think @siradji 

```
<div className='animate-pulse bg-gray-200 rounded w-min cursor-default'>
  <p className='opacity-0'>$3.03</p>
</div>
 ```

**Comment by siradji** [comment]
@joeldavidw it's done

**Comment by joeldavidw** [comment]
I am unable to see the loaders

image

**Comment by siradji** [comment]
@joel fixed
image

**Pull request closed without merging**
