### PR TITLE
Tyrkson/update token symbols

### LINKED ISSUE #800: Update all `token` symbols
#### What would you like to be added:

To update the token symbols to make them 100% utilitarian and not resort to using brand colours and logos.

Required Features:

- Dynamic component similar to [`_Default` ](https://github.com/DeFiCh/scan/blob/main/src/components/icons/assets/tokens/_Default.tsx)
- Font Size based on the length of the text

<details>
<summary>Example Image</summary>

telegram-cloud-photo-size-5-6244467288711474915-x

</details>

/triage accepted
/area ui-ux

### PR DESCRIPTION
**Pull request by Tyrkson**
#### What kind of PR is this?:

/kind feature

#### What this PR does / why we need it:

Updates all token symbols to a black circle with white text

#### Which issue(s) does this PR fixes?:

Fixes #800 

#### Sample Links & Screenshots:

Link: 
<details>
<summary>Desktop Screenshot</summary>

image

</details>
<details>
<summary>Mobile Screenshot</summary>

image

</details>

#### Developer Checklist:

- [x] Read your code changes at least once
- [x] Tested on multiple web browsers
- [x] Tested responsiveness (e.g, iPhone, iPad, Desktop)
- [x] No console errors
- [ ] Unit tests*
- [ ] Added e2e tests*

### CODE REVIEW

**Comment by Tyrkson** [comment]
I'm not sure did I have to change the symbols shown on mobile screenshot as well. That's also why I left the PR on draft mode right now.

**Comment by joeldavidw** [comment]
Thanks @Tyrkson! I will check with the team regrading those pair symbols.

**Comment by joeldavidw** [comment]
@Tyrkson Got an update from the team. We will also be updating the design of the LPs tokens. Similar to loan tokens but with 2 lines instead as shown below.

<details>
<summary>LP Token</summary>

IMAGE 2022-01-18 16:44:22



</details>

**Comment by Tyrkson** [comment]
I didn't remove dGME, dBABA etc custom symbol files but If they aren't needed anymore then I can do that as well.

**Review by joeldavidw — APPROVED** [review]

**Pull request merged**
